### ISSUE TITLE
Request for kernel source code for Moto G Play (maui, S3SG32.39-191)

### ISSUE THREAD

**Issue by dynamikmechanik** [MotorolaMobilityLLC/kernel-mtk#101]
Hi, I am a developer who is interested in working on the Moto G Play. I would like to request the kernel source code for the device with the following specifications:

- Model: Moto G Play
- Build Number: S3SG32.39-191
- Codename: maui

I would appreciate it if you could provide me with the kernel source code for this device. Thank you for your time.

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3SG32.39-191R2

**Comment by zamboni33** [comment]
I was able to get this kernel building pretty quickly but without thinking I built it for aarch64 instead of arm. I ran into problems trying to build the 32-bit version but that is what came on my device. Any help on getting the right toolchain and environment for 32-bit would be appreciated greatly.

I am assuming a 64-bit build would not work given the released image is 32-bit. Is that incorrect?
