### ISSUE TITLE
Camera hals broken

### ISSUE THREAD

**Issue by PainKiller3** [MotorolaMobilityLLC/kernel-mtk#14]
Please fix the camera hals as fast as possible the camera show blank 
camera drivers missing

**Comment by PainKiller3** [comment]
Btw device name is moto M

**Comment by PainKiller3** [comment]
@chenyt9
please have a look...
kernel source for moto M (XT1663) is incomplete..
camera stuff is missing...

**Comment by chenyt9** [comment]
@PainKiller3 ，Hello, I would like to confirm again, I did publish the entire kernel repo, did you follow this process to compile the code? https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-XT1663-S0124-161215.txt

**Comment by PainKiller3** [comment]
Well i will try that and tell u

**Comment by PainKiller3** [comment]
Doesn't work still same : ( @chenyt9

**Comment by chenyt9** [comment]
@PainKiller3，please confirm that you are using the correct tag version: MMI-XT1663-S356-170621.
Thanks.

**Comment by PainKiller3** [comment]
@chenyt9 yes i m using this tag https://github.com/MotorolaMobilityLLC/kernel-mtk/tree/MMI-XT1663-S356-170621

**Comment by chenyt9** [comment]
@PainKiller3, camera stuff in uder the path:drivers/misc/mediatek/imgsensor. Can you provide your compile command? Thanks.

**Comment by chenyt9** [comment]
@PainKiller3 , I fetch the code and try to compile and find a file missing two definitions:
The error message is:
'SENSOR_DRVNAME_S5K3M2_SUNNY_MIPI_RAW' undeclared here (not in a function)
'SENSOR_DRVNAME_OV8865_SUNNY_MIPI_RAW' undeclared here (not in a function)
If you have the same error message as me, please add the following two lines to the file "drivers/misc/mediatek/imgsensor/inc":
#define  SENSOR_DRVNAME_OV8865_SUNNY_MIPI_RAW         "ov8865sunnymipiraw "
#define SENSOR_DRVNAME_S5K3M2_SUNNY_MIPI_RAW          "s5k3m2sunnymipiraw "
If your error message is not the same, please send your build command and build log to me. I will update the readme file and update the two lines of code to the source file. If you still have questions, please contact me.

**Comment by chenyt9** [comment]
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-XT1663-S356-170621.txt

**Comment by Pipaolo** [comment]
@chenyt9 I tried adding that, it compiled successfully. But when i flashed it to test. The camera won't work for some reason. :/

**Comment by PainKiller3** [comment]
@chenyt9  the camera is not working even after following the steps given in the text file : ( pls fix the code : ( thanks

**Comment by chenyt9** [comment]
@PainKiller3  @Pipaolo , maybe it's because of a missing macro control. Please add this definition when compiling: TARGET_PRODUCT := kungfu_m。
Please try it. If you still have problems, please let me know. I would like to know how you guys perform the brushing and please send me your compiler instructions and flashing steps. I try to find another reason from elsewhere. Thanks.

**Comment by Pipaolo** [comment]
@chenyt9 I tried adding that an error happened "make: *** empty variable name.  Stop."

**Comment by chenyt9** [comment]
@Pipaolo , are you compiled according to the steps of this document ( https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-XT1663-S356-170621.txt ) ? I did not encounter the situation as you said, I added "TARGET_PRODUCT := kungfu_m" in the makefile, or you directly export TARGET_PRODUCT=kungfu_m.
Or, you can send me your build command.

**Comment by Pipaolo** [comment]
@chenyt9 where do I add "TARGET_PRODUCT := kungfu_m"?  I literally added that in the make command.
(EDIT)
It compiled successfully and the camera is working now. By the way I find it weird that the camera error did not appeared. Even though I didn't edit the kd_imgsensor.h file.

**Comment by chenyt9** [comment]
@Pipaolo , I think it is also possible, but I directly export this variable, or choose to add in the Android.mk file in the root directory of the kernel...I think there are many ways, as long as it can be read.  
Because we didn't compile the camera code before, we use this variable to control the camera's compilation，You can look at the makefile below these paths, search for this variable, and you will understand:
Kernel-3.18/drivers/misc/mediatek/flashlight/src/mt6755
Kernel-3.18/drivers/misc/mediatek/imgsensor/src/mt6755
Kernel-3.18/drivers/misc/mediatek/imgsensor/src/mt6755/camera_hw
Thanks.
