### ISSUE TITLE
Moto C Plus issue

### ISSUE THREAD

**Issue by mahendrapardeshi** [MotorolaMobilityLLC/kernel-mtk#26]
Hi,
One month back bought Moto C Plus it keep hanging frequently to resolve it tried following things -

1) Perform factory reset.
2) Perform wiped catch data.
3) volte option turn off
4) Replace Jio  4G sim two time.
5) updated to  NRD90M.03.041 

Please help to resolve the issue.

Thanks

**Comment by awheeler-mmi** [comment]
Hey @mahendrapardeshi .   I am sorry your phone is give you trouble.  Can you direct your query to the [support form](https://forums.lenovo.com/t5/Moto-C-Phones/ct-p/Moto_C_Phones)?  Device hangs can be due to many different issues, and the support forum is the best place to work out the issues.  I did not personally work on the Moto C Plus, but you've gone through all the steps I would recommend before suggesting you check out the support forums.

Thanks - and good luck!

-andrew
